//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8933
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Layouts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layouts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.Layouts", typeof(Layouts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.317928505605897&quot; DockRightPortion=&quot;0.30369273580168&quot; DockTopPortion=&quot;0.354512676472017&quot; DockBottomPortion=&quot;0.611372184935232&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;7&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.AccountForm|InstanceId=StockTermina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AAStockAdvancedLayout {
            get {
                return ResourceManager.GetString("AAStockAdvancedLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.347095172272564&quot; DockRightPortion=&quot;0.23630992330168&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.394002134367957&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;6&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.AccountForm|InstanceId=StockTerminal_Forms_Accou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AAStockStandardLayout {
            get {
                return ResourceManager.GetString("AAStockStandardLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.193817630426631&quot; DockRightPortion=&quot;0.287785717532645&quot; DockTopPortion=&quot;0.395838060240072&quot; DockBottomPortion=&quot;0.604161939759928&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;7&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.AccountForm|InstanceId=StockTermin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.275741005605897&quot; DockRightPortion=&quot;0.23728648580168&quot; DockTopPortion=&quot;0.354512676472017&quot; DockBottomPortion=&quot;0.645487323527983&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;7&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.AccountForm|InstanceId=StockTermina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advanced_Client {
            get {
                return ResourceManager.GetString("Advanced_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.347095172272564&quot; DockRightPortion=&quot;0.23728648580168&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.533309069224881&quot; ActiveDocumentPane=&quot;5&quot; ActivePane=&quot;5&quot;&gt;
        ///  &lt;Contents Count=&quot;3&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.EventForm|InstanceId=StockTerminal_Forms_EventForm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Compact {
            get {
                return ResourceManager.GetString("Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.347095172272564&quot; DockRightPortion=&quot;0.23728648580168&quot; DockTopPortion=&quot;0.518882175226586&quot; DockBottomPortion=&quot;0.481117824773414&quot; ActiveDocumentPane=&quot;11&quot; ActivePane=&quot;11&quot;&gt;
        ///  &lt;Contents Count=&quot;6&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.StockQuoteForm|InstanceId=StockTerm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteOnly {
            get {
                return ResourceManager.GetString("QuoteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.347095172272564&quot; DockRightPortion=&quot;0.23728648580168&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.485447562096571&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;6&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.AccountForm|InstanceId=StockTerminal_Forms_Accou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.347095172272564&quot; DockRightPortion=&quot;0.23435679830168&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.371614709070634&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;6&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;StockTerminal.Forms.AccountForm|InstanceId=StockTerminal_Forms_Accou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Standard_Client {
            get {
                return ResourceManager.GetString("Standard_Client", resourceCulture);
            }
        }
    }
}
