//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.LoginForm_", typeof(LoginForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Login_Message_Connecting {
            get {
                return ResourceManager.GetString("Login_Message_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect server.
        /// </summary>
        internal static string Login_Message_FailedToConnectServer {
            get {
                return ResourceManager.GetString("Login_Message_FailedToConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data.
        /// </summary>
        internal static string Login_Message_FailedToLoadData {
            get {
                return ResourceManager.GetString("Login_Message_FailedToLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced to logout.
        /// </summary>
        internal static string Login_Message_ForceLogout {
            get {
                return ResourceManager.GetString("Login_Message_ForceLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id or Password is not correct.
        /// </summary>
        internal static string Login_Message_InvalidUserIdPassword {
            get {
                return ResourceManager.GetString("Login_Message_InvalidUserIdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code is not correct.
        /// </summary>
        internal static string Login_Message_InvalidVerificationCode {
            get {
                return ResourceManager.GetString("Login_Message_InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data....
        /// </summary>
        internal static string Login_Message_Loading {
            get {
                return ResourceManager.GetString("Login_Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress....
        /// </summary>
        internal static string Login_Message_Login {
            get {
                return ResourceManager.GetString("Login_Message_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After changing your password, use your new password to login.
        /// </summary>
        internal static string Login_Message_PasswordForceChange {
            get {
                return ResourceManager.GetString("Login_Message_PasswordForceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send Verification Code to your email.
        /// </summary>
        internal static string Login_Message_ResendVerificationCodeEmail {
            get {
                return ResourceManager.GetString("Login_Message_ResendVerificationCodeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send Verification Code to your mobile.
        /// </summary>
        internal static string Login_Message_ResendVerificationCodeSMS {
            get {
                return ResourceManager.GetString("Login_Message_ResendVerificationCodeSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code is being sent to your email.
        /// </summary>
        internal static string Login_Message_SendingVerificationCodeEmail {
            get {
                return ResourceManager.GetString("Login_Message_SendingVerificationCodeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code is being sent to your mobile.
        /// </summary>
        internal static string Login_Message_SendingVerificationCodeSMS {
            get {
                return ResourceManager.GetString("Login_Message_SendingVerificationCodeSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service closed.
        /// </summary>
        internal static string Login_Message_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Login_Message_ServiceUnavailable", resourceCulture);
            }
        }
    }
}
