//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8936
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.MainForm_", typeof(MainForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Terminal.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Terminal.
        /// </summary>
        internal static string DocumentNameQuote {
            get {
                return ResourceManager.GetString("DocumentNameQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not been using Stock Terminal for more than {0:0} minutes. Terminal will logout automatically within {1:0} minute. Logout now?.
        /// </summary>
        internal static string MsgBoxConfirmAutoLogout {
            get {
                return ResourceManager.GetString("MsgBoxConfirmAutoLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to exit?.
        /// </summary>
        internal static string MsgBoxConfirmExit {
            get {
                return ResourceManager.GetString("MsgBoxConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to logout?.
        /// </summary>
        internal static string MsgBoxConfirmLogout {
            get {
                return ResourceManager.GetString("MsgBoxConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ToolStripStatusTradeDB_Connecting {
            get {
                return ResourceManager.GetString("ToolStripStatusTradeDB_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        internal static string ToolStripStatusTradeDB_Disconnecting {
            get {
                return ResourceManager.GetString("ToolStripStatusTradeDB_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress....
        /// </summary>
        internal static string ToolStripStatusTradeDB_Login {
            get {
                return ResourceManager.GetString("ToolStripStatusTradeDB_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ToolStripStatusTradeDB_Ready {
            get {
                return ResourceManager.GetString("ToolStripStatusTradeDB_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string ToolStripStatusTradeDB_Stopped {
            get {
                return ResourceManager.GetString("ToolStripStatusTradeDB_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        internal static string UserTypeAE {
            get {
                return ResourceManager.GetString("UserTypeAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string UserTypeClient {
            get {
                return ResourceManager.GetString("UserTypeClient", resourceCulture);
            }
        }
    }
}
