//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderBookForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderBookForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.OrderBookForm_", typeof(OrderBookForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1s.
        /// </summary>
        internal static string AllOrder_AAmendOrderDown {
            get {
                return ResourceManager.GetString("AllOrder_AAmendOrderDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amd -1s.
        /// </summary>
        internal static string AllOrder_AAmendOrderDownHeader {
            get {
                return ResourceManager.GetString("AllOrder_AAmendOrderDownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1s.
        /// </summary>
        internal static string AllOrder_AAmendOrderUp {
            get {
                return ResourceManager.GetString("AllOrder_AAmendOrderUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amd +1s.
        /// </summary>
        internal static string AllOrder_AAmendOrderUpHeader {
            get {
                return ResourceManager.GetString("AllOrder_AAmendOrderUpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AllOrder_AccountNo {
            get {
                return ResourceManager.GetString("AllOrder_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        internal static string AllOrder_AECode {
            get {
                return ResourceManager.GetString("AllOrder_AECode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Price.
        /// </summary>
        internal static string AllOrder_AvgPrice {
            get {
                return ResourceManager.GetString("AllOrder_AvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AllOrder_DeleteBtnVal {
            get {
                return ResourceManager.GetString("AllOrder_DeleteBtnVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AllOrder_DeleteOrder {
            get {
                return ResourceManager.GetString("AllOrder_DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EX.
        /// </summary>
        internal static string AllOrder_Exchange {
            get {
                return ResourceManager.GetString("AllOrder_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        internal static string AllOrder_Filled_Qty {
            get {
                return ResourceManager.GetString("AllOrder_Filled_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Action.
        /// </summary>
        internal static string AllOrder_LastAction {
            get {
                return ResourceManager.GetString("AllOrder_LastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string AllOrder_Memo {
            get {
                return ResourceManager.GetString("AllOrder_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string AllOrder_Order_Price {
            get {
                return ResourceManager.GetString("AllOrder_Order_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string AllOrder_Order_Qty {
            get {
                return ResourceManager.GetString("AllOrder_Order_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        internal static string AllOrder_Order_Side {
            get {
                return ResourceManager.GetString("AllOrder_Order_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        internal static string AllOrder_Orderno {
            get {
                return ResourceManager.GetString("AllOrder_Orderno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AllOrder_OrderStatus {
            get {
                return ResourceManager.GetString("AllOrder_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        internal static string AllOrder_OrderType {
            get {
                return ResourceManager.GetString("AllOrder_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replied.
        /// </summary>
        internal static string AllOrder_Reply {
            get {
                return ResourceManager.GetString("AllOrder_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string AllOrder_Status_Msg {
            get {
                return ResourceManager.GetString("AllOrder_Status_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string AllOrder_StockCode {
            get {
                return ResourceManager.GetString("AllOrder_StockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amend.
        /// </summary>
        internal static string Amend {
            get {
                return ResourceManager.GetString("Amend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete order: #.
        /// </summary>
        internal static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Checking.
        /// </summary>
        internal static string CreditChecking {
            get {
                return ResourceManager.GetString("CreditChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Failed.
        /// </summary>
        internal static string CreditFailed {
            get {
                return ResourceManager.GetString("CreditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Pass.
        /// </summary>
        internal static string CreditPass {
            get {
                return ResourceManager.GetString("CreditPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker ID.
        /// </summary>
        internal static string Deal_BrokerId {
            get {
                return ResourceManager.GetString("Deal_BrokerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        internal static string Deal_BuySell {
            get {
                return ResourceManager.GetString("Deal_BuySell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        internal static string Deal_FilledQty {
            get {
                return ResourceManager.GetString("Deal_FilledQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal No..
        /// </summary>
        internal static string Deal_No {
            get {
                return ResourceManager.GetString("Deal_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Qty.
        /// </summary>
        internal static string Deal_OrderQty {
            get {
                return ResourceManager.GetString("Deal_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Deal_Price {
            get {
                return ResourceManager.GetString("Deal_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Deal_Qty {
            get {
                return ResourceManager.GetString("Deal_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Deal_StkCode {
            get {
                return ResourceManager.GetString("Deal_StkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Deal_Time {
            get {
                return ResourceManager.GetString("Deal_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Book.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputError.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Trade Password.
        /// </summary>
        internal static string InvalidTradePass {
            get {
                return ResourceManager.GetString("InvalidTradePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Completed.
        /// </summary>
        internal static string PartiallyCompleted {
            get {
                return ResourceManager.GetString("PartiallyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected By OG.
        /// </summary>
        internal static string RejectedByOG {
            get {
                return ResourceManager.GetString("RejectedByOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected By Supervisor.
        /// </summary>
        internal static string RejectedBySupervisor {
            get {
                return ResourceManager.GetString("RejectedBySupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Fail.
        /// </summary>
        internal static string SendFail {
            get {
                return ResourceManager.GetString("SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Success.
        /// </summary>
        internal static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To OG.
        /// </summary>
        internal static string SentToOG {
            get {
                return ResourceManager.GetString("SentToOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
