//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReconnectForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReconnectForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.ReconnectForm_", typeof(ReconnectForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting....
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ImageError {
            get {
                object obj = ResourceManager.GetObject("ImageError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageExclamation {
            get {
                object obj = ResourceManager.GetObject("ImageExclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageInformation {
            get {
                object obj = ResourceManager.GetObject("ImageInformation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageQuestion {
            get {
                object obj = ResourceManager.GetObject("ImageQuestion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network reconnected..
        /// </summary>
        internal static string Reconnect_Message_Reconnected {
            get {
                return ResourceManager.GetString("Reconnect_Message_Reconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection is broken. Reconnecting....
        /// </summary>
        internal static string Reconnect_Message_Reconnecting {
            get {
                return ResourceManager.GetString("Reconnect_Message_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection is broken. Please logout and login again..
        /// </summary>
        internal static string Reconnect_Message_Relogin {
            get {
                return ResourceManager.GetString("Reconnect_Message_Relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Reconnect_Status_Connecting {
            get {
                return ResourceManager.GetString("Reconnect_Status_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect server.
        /// </summary>
        internal static string Reconnect_Status_FailedToConnectServer {
            get {
                return ResourceManager.GetString("Reconnect_Status_FailedToConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id or Password is not correct.
        /// </summary>
        internal static string Reconnect_Status_InvalidUserIdPassword {
            get {
                return ResourceManager.GetString("Reconnect_Status_InvalidUserIdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress....
        /// </summary>
        internal static string Reconnect_Status_Login {
            get {
                return ResourceManager.GetString("Reconnect_Status_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sucess..
        /// </summary>
        internal static string Reconnect_Status_Ready {
            get {
                return ResourceManager.GetString("Reconnect_Status_Ready", resourceCulture);
            }
        }
    }
}
