//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8941
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StockQuoteForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockQuoteForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.StockQuoteForm_", typeof(StockQuoteForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-in.
        /// </summary>
        internal static string AllIn {
            get {
                return ResourceManager.GetString("AllIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        internal static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Buy .
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Buy) .
        /// </summary>
        internal static string Buy2 {
            get {
                return ResourceManager.GetString("Buy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS.
        /// </summary>
        internal static string CAS {
            get {
                return ResourceManager.GetString("CAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quote.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Stock.
        /// </summary>
        internal static string GrayStock {
            get {
                return ResourceManager.GetString("GrayStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Insufficient buying power ---.
        /// </summary>
        internal static string Insufficientbuyingpower {
            get {
                return ResourceManager.GetString("Insufficientbuyingpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Invalid account number ---.
        /// </summary>
        internal static string Invalidaccountnumber {
            get {
                return ResourceManager.GetString("Invalidaccountnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Invalid stock code ---.
        /// </summary>
        internal static string Invalidstockcode {
            get {
                return ResourceManager.GetString("Invalidstockcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- No stock on hand ---.
        /// </summary>
        internal static string Nostockonhand {
            get {
                return ResourceManager.GetString("Nostockonhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sell .
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sell) .
        /// </summary>
        internal static string Sell2 {
            get {
                return ResourceManager.GetString("Sell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sell .
        /// </summary>
        internal static string Sell3 {
            get {
                return ResourceManager.GetString("Sell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Support HK Stocks Only ---.
        /// </summary>
        internal static string SupportHKStockOnly {
            get {
                return ResourceManager.GetString("SupportHKStockOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusing.
        /// </summary>
        internal static string TradeStatusFusing {
            get {
                return ResourceManager.GetString("TradeStatusFusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string TradeStatusSuspended {
            get {
                return ResourceManager.GetString("TradeStatusSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling.
        /// </summary>
        internal static string VCMCooling {
            get {
                return ResourceManager.GetString("VCMCooling", resourceCulture);
            }
        }
    }
}
