//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TotalAmtLimitForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TotalAmtLimitForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Forms.TotalAmtLimitForm_", typeof(TotalAmtLimitForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount = .
        /// </summary>
        internal static string ConfirmMsg1 {
            get {
                return ResourceManager.GetString("ConfirmMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which is &gt; .
        /// </summary>
        internal static string ConfirmMsg2 {
            get {
                return ResourceManager.GetString("ConfirmMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Accept?.
        /// </summary>
        internal static string ConfirmMsg3 {
            get {
                return ResourceManager.GetString("ConfirmMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [258] to Accept, [Esc] to Cancel.
        /// </summary>
        internal static string ConfirmMsg4 {
            get {
                return ResourceManager.GetString("ConfirmMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code:.
        /// </summary>
        internal static string ConfirmMsg5 {
            get {
                return ResourceManager.GetString("ConfirmMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade SZ ChiNext stock?.
        /// </summary>
        internal static string ConfirmMsg6 {
            get {
                return ResourceManager.GetString("ConfirmMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
    }
}
