//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTerminal.Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DailyReportDetailsForm_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DailyReportDetailsForm_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTerminal.Report.DailyReportDetailsForm_", typeof(DailyReportDetailsForm_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string AccNoHead {
            get {
                return ResourceManager.GetString("AccNoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Price.
        /// </summary>
        internal static string AvgPriceHead {
            get {
                return ResourceManager.GetString("AvgPriceHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        internal static string BuySellHead {
            get {
                return ResourceManager.GetString("BuySellHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Checking.
        /// </summary>
        internal static string CreditChecking {
            get {
                return ResourceManager.GetString("CreditChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Failed.
        /// </summary>
        internal static string CreditFailed {
            get {
                return ResourceManager.GetString("CreditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Pass.
        /// </summary>
        internal static string CreditPass {
            get {
                return ResourceManager.GetString("CreditPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Trade Report.
        /// </summary>
        internal static string DailyTradeRptTittle {
            get {
                return ResourceManager.GetString("DailyTradeRptTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EX.
        /// </summary>
        internal static string ExchangeCodeHead {
            get {
                return ResourceManager.GetString("ExchangeCodeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputError.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Trade Password.
        /// </summary>
        internal static string InvalidTradePass {
            get {
                return ResourceManager.GetString("InvalidTradePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity.
        /// </summary>
        internal static string LastActionPlacedByHead {
            get {
                return ResourceManager.GetString("LastActionPlacedByHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        internal static string OrderNoHead {
            get {
                return ResourceManager.GetString("OrderNoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Time.
        /// </summary>
        internal static string OrderPlaceDateTimeHead {
            get {
                return ResourceManager.GetString("OrderPlaceDateTimeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed By.
        /// </summary>
        internal static string OrderPlacedByHead {
            get {
                return ResourceManager.GetString("OrderPlacedByHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price.
        /// </summary>
        internal static string OrderPriceHead {
            get {
                return ResourceManager.GetString("OrderPriceHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Qty.
        /// </summary>
        internal static string OrderQtyHead {
            get {
                return ResourceManager.GetString("OrderQtyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string OrderStatusHead {
            get {
                return ResourceManager.GetString("OrderStatusHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Completed.
        /// </summary>
        internal static string PartiallyCompleted {
            get {
                return ResourceManager.GetString("PartiallyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Qty.
        /// </summary>
        internal static string QtyHead {
            get {
                return ResourceManager.GetString("QtyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected By OG.
        /// </summary>
        internal static string RejectedByOG {
            get {
                return ResourceManager.GetString("RejectedByOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected By Supervisor.
        /// </summary>
        internal static string RejectedBySupervisor {
            get {
                return ResourceManager.GetString("RejectedBySupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Fail.
        /// </summary>
        internal static string SendFail {
            get {
                return ResourceManager.GetString("SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Success.
        /// </summary>
        internal static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To OG.
        /// </summary>
        internal static string SentToOG {
            get {
                return ResourceManager.GetString("SentToOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string StkCodeHead {
            get {
                return ResourceManager.GetString("StkCodeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
