[TradeDB]
# Production 1
LoginHost01 = 192.1.2.13
LoginPort01 = 80

# Production 2
LoginHost02 = www.pru.hk
LoginPort02 = 443

# Production 3
LoginHost03 = www.pru.com.hk
LoginPort03 = 443

LogMessage328=1
